name = "threejs-game"
main = "_worker.js"
compatibility_date = "2024-04-30"

[site]
bucket = "./dist"
include = [
  "**/*.js",
  "**/*.html",
  "**/*.css",
  "**/*.gltf",
  "**/*.fbx",
  "**/*.obj",
  "**/*.mtl",
  "**/*.jpg",
  "**/*.png",
  "**/*.mp3",
  "**/*.wav",
  "**/*.json"
]
exclude = [
  "mode/roamGirl copy.glb"
]

[build]
command = "npm run build"
watch_dir = "build"

[env.production]
name = "threejs-game-prod"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[r2_buckets]]
binding = 'ASSETS'
bucket_name = 'threejs-game-assets'
preview_bucket_name = 'threejs-game-assets-dev' 